openapi: 3.0.0
info:
  title: Exemplo de API
  description: API de exemplo usando Swagger com Express
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Retorna uma saudação
      responses:
        '200':
          description: Resposta com saudação
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Olá, mundo!"
